eventManager/config/routes.rb
Rails.application.routes.draw do
  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  match '/logout',  to: 'sessions#destroy', via: 'delete'

  match '/signup',    to: 'users#new',    via: 'get'
  match '/welcome',    to: 'welcome#show',    via: 'get'
  root 'welcome#index'

  match '/admin',    to: 'admin#show',    via: 'get'
  
  match 'assigned_characters/:character_id/:event_id',    to: 'assigned_characters#create',    via: 'post', as: :assign

  resources :attendances, only: [:create, :index]
  resources :users
  resources :events
  resources :places
  resources :welcome, only: [:show, :index]
  resources :posts
  resources :organizations
  resources :characters
  resources :user_organizations, only: [:create, :index]
  resources :assigned_characters
  resources :admin, only: [:show]
  resources :event_admin_panels, only: [:index]

end

eventManager/app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :user_organizations
  has_many :users, :through => :user_organizations
  has_many :posts
  has_many :characters
  has_many :events
end

eventManager/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  def index
    @organizations = Organization.all
  end
  # GET /organizations/1
  def show    
    @organization = Organization.find(params[:id])    
  end
  # GET /organizations/new
  def new    
    @organization = Organization.new    
    @user = current_user
  end
  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])     
  end
  # POST /organizations
  def create
    @organization = Organization.new(organization_params)
    respond_to do |format|
      if @organization.save
        if current_user != "superadmin"
          current_user.works_at(@organization)
        end
        format.html { redirect_to @organization, notice: 'Organization was successfully created and your are now part of it' }

      else
        format.html { render :new }
      end
    end
  end
  # PATCH/PUT /organizations/1
  def update
    @user = current_user
    @organization = Organization.find(params[:id])
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  # DELETE /organizations/1
  def destroy
   @organization = Organization.find(params[:id])
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
    end
  end

  private
    def organization_params
      params.require(:organization).permit(
        :name, :description, :url, :creator_id)
    end
end

eventManager/app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="input-group">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="input-group">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <%= f.hidden_field :creator_id, :value => current_user.id %>
  <div>
    <br><%= f.submit %>
  </div>
<% end %>

eventManager/app/views/organizations/_index.html.erb
<div class="alert alert-info">
  <h2>Listing Organizations</h2>
  <%= link_to 'New Organization', new_organization_path, role: "button", class: "btn btn-success" %>
</div>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Url</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @organizations.each do |organization| %>
        <tr>
          <td><%= organization.name %> <br> </td>
          <td><%= organization.description %> <br> </td>
          <td><a target ="blank" href=<%= organization.url %>><%= organization.url %></a> <br> </td>
          <td><%= link_to 'Show', organization, role: "button", class: "btn btn-default" %> <br> </td>
          <% if current_user.role === "admin" %>
            <td><%= link_to 'Edit', edit_organization_path(organization), role: "button", class: "btn btn-default"%> <br> </td>
            <td><%= link_to 'Destroy', organization, method: :delete, role: "button", class: "btn btn-default", data: { confirm: 'Are you sure?' } %> </td>
            <td><%= link_to 'Ask for Join', user_organizations_path(organization_id: organization.id), method: :post, role: "button", class: "btn btn-success"%> <br> </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>    
  </table>
</div>
  

eventManager/app/views/organizations/edit.html.erb
<div class="col-xs-4">
  <h1 class="bg-primary">Editing Organization</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @organization %> |
  <%= link_to 'Back', organizations_path %>
</div>

eventManager/app/views/organizations/index.html.erb
<%= render "index" %>

eventManager/app/views/organizations/new.html.erb
<div class="col-xs-4">
  <h1 class="bg-primary">New Organization</h1>

  <%= render 'form' %>

  <%= link_to 'Back', organizations_path %>
</div>

eventManager/app/views/organizations/show.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="well">
      <strong>Name:</strong>
      <%= @organization.name %>
    </div>
    <div class="well">
      <strong>Description:</strong>
      <%= @organization.description %>
    </div>
    <div class="well">
      <strong>Url:</strong>
      <a target ="blank" href=<%= @organization.url %>><%= @organization.url %></a> 
    </div>
    <% if (current_user.role === "admin") %>
      <%= link_to 'Edit', edit_organization_path(@organization) %> |
    <%end%>
    <%= link_to 'Back', organizations_path %>
  </div>
</div>