eventManager/config/routes.rb
Rails.application.routes.draw do
  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  match '/logout',  to: 'sessions#destroy', via: 'delete'

  match '/signup',    to: 'users#new',    via: 'get'
  match '/welcome',    to: 'welcome#show',    via: 'get'
  root 'welcome#index'

  match '/admin',    to: 'admin#show',    via: 'get'
  
  match 'assigned_characters/:character_id/:event_id',    to: 'assigned_characters#create',    via: 'post', as: :assign

  resources :attendances, only: [:create, :index]
  resources :users
  resources :events
  resources :places
  resources :welcome, only: [:show, :index]
  resources :posts
  resources :organizations
  resources :characters
  resources :user_organizations, only: [:create, :index]
  resources :assigned_characters
  resources :admin, only: [:show]
  resources :event_admin_panels, only: [:index]

end

eventManager/app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
  has_many :assigned_characters
  has_many :events, :through => :assigned_characters
  has_many :posts

  def is_part_of(event)
    assigned_characters.create(event_id: event.id)
  end
end

eventManager/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  def index
    @characters = Character.all       
  end
  # GET /characters/1
  def show
    @character = Character.find(params[:id])
    @creator = User.all.find(@character.creator_id) if @character.creator_id
    @user = User.all.find(@character.user_id) if @character.user_id
    @organization = Organization.all.find(@character.organization_id) if @character.organization_id
    @posts = Post.where(character_id: params[:id])
    @post = @posts.last
  end
  # GET /characters/new
  def new    
    @character = Character.new
    @user = current_user
    @organizations = @user.organizations  
    @event = Event.find(params[:event_id]) if params[:event_id]
  end
  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end
  # POST /characters
  def create
    @character = Character.new(character_params)
    @user = current_user
    @event = Event.find(params[:event_id]) if :event_id    
    respond_to do |format|
      if @character.save 
        @character.is_part_of(@event) if @event      
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  # PATCH/PUT /characters/1
  def update
    @user = current_user
    @character = Character.find(params[:id])
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  # DELETE /characters/1
  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
    end
  end
    
  private
    def character_params
      params.require(:character).permit(
        :name, :introduction, :user_id, :organization_id, :creator_id)
    end
end

eventManager/app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>
      <ul>
        <% @character.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :introduction %><br>
    <%= f.text_field :introduction %>
  </div>  
  <%= f.hidden_field :creator_id, :value => current_user.id %>
  <div class="form-group">
    Organization: <br>
    <%= (f.select :organization_id, current_user.organizations.collect { |p| [ p.name, p.id ] }, include_blank: true) if current_user.organizations %>
  </div>
  <% if @event %>
    <div>      
      <%= hidden_field_tag 'event_id', @event.id %>
      <%= f.submit %>
    </div>
  <% else %>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

eventManager/app/views/characters/_index.html.erb
<div class="alert alert-info">
  <%if @event%>    
    <h2>Characters of <%= @event.name%> event</h2><br>
    <%= link_to 'New Character', new_character_path(event_id: @event.id), role: "button", class: "btn btn-success"%>
  <%else%>
    <%= link_to 'New Character', new_character_path, role: "button", class: "btn btn-success"  %>
  <%end%>
</div>
<div class="table-responsive">
    <%if @characters%>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Introduction</th>
            <th>Event</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @characters.each do |character|%>
            <tr>
              <td><%= character.name if character.name%> <br> </td>
              <td><%= character.introduction %> <br> </td>    
              <% if current_user && ((current_user.role === "admin") || (character.creator_id === current_user.id) || (character.user_id === current_user.id)) %>    
                <td><%= character.events.last.name if character.events.last %> <br> </td> 
                <td><%= link_to 'Show', character, role: "button", class: "btn btn-default" %> <br> </td>
              <% end %>
              <% if current_user && ((current_user.role === "admin") || (character.creator_id === current_user.id)) %>
                <td><%= link_to 'Edit', edit_character_path(character), role: "button", class: "btn btn-default" %> <br> </td>
                <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' }, role: "button", class: "btn btn-default" %> </td>
                <% if @event && @event.id != character.organization_id%>
                  <td><%= link_to 'Add to this event', assign_url(character_id: character.id, event_id: @event.id), method: :post, role: "button", class: "btn btn-success"%> <br> </td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table><br>
    <% else %>
      <div class="alert alert-warning">
        You have no characters yet.
      </div>
    <% end %>
 </div> 

eventManager/app/views/characters/edit.html.erb
<div class="col-xs-4">
  <h2>Editing Character</h2>
  
  <%= render 'form' %>

  <%= link_to 'Show', @character %> |
  <%= link_to 'Back', characters_path %>
</div>

eventManager/app/views/characters/index.html.erb
<%= render "index" %>

eventManager/app/views/characters/new.html.erb
<div class="col-xs-4">
  <h1 class="bg-primary">New Character</h1>

  <%= render 'form' %>

  <%= link_to 'Back', characters_path %>
</div>

eventManager/app/views/characters/show.html.erb
<div class="col-xs-4">
  <div class="well">
    <strong>Name:</strong></br>
    <%= @character.name %>
  </div>
  <div class="well">
    <strong>Introduction:</strong></br>
    <%= @character.introduction %>
  </div>
  <div class="well">
    <strong>Creator:</strong></br>
    <%= @creator.name if @creator%>
  </div>
  <div class="well">
    <strong>Player:</strong></br>
    <%= @user.name if @user%>
  </div>
  <div class="well">
    <strong>Organization:</strong></br>
    <%= @organization.name if @organization%>
  </div>
  <div class="well">
    <strong>Event:</strong></br>
    <%= @character.events.last.name if @character.events.last %>
  </div>
  <% if current_user && ((current_user.role === "admin") || (@character.creator_id === current_user.id)) %>
    <%= link_to 'Edit', edit_character_path(@character) %> |
  <% end %>
  <%= link_to 'Back', characters_path %>
</div>
<div class="col-xs-8">    
  <% if @posts && @post%>
    <%= render partial: "posts/index", :locals => {:character => @character}  %>
    <%= render partial: "posts/show", :locals => {:character => @character}  %>
  <%end%>  
</div>