eventManager/config/routes.rb
Rails.application.routes.draw do
  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  match '/logout',  to: 'sessions#destroy', via: 'delete'

  match '/signup',    to: 'users#new',    via: 'get'
  match '/welcome',    to: 'welcome#show',    via: 'get'
  root 'welcome#index'

  match '/admin',    to: 'admin#show',    via: 'get'
  
  match 'assigned_characters/:character_id/:event_id',    to: 'assigned_characters#create',    via: 'post', as: :assign

  resources :attendances, only: [:create, :index]
  resources :users
  resources :events
  resources :places
  resources :welcome, only: [:show, :index]
  resources :posts
  resources :organizations
  resources :characters
  resources :user_organizations, only: [:create, :index]
  resources :assigned_characters
  resources :admin, only: [:show]
  resources :event_admin_panels, only: [:index]

end

eventManager/app/models/event.rb
class Event < ActiveRecord::Base
	scope :future_events, -> (date) {where('begin_date > ?', date)}
	has_many :attendances
	has_many :users, :through => :attendances
  belongs_to :place
  has_many :assigned_characters
  has_many :characters, :through => :assigned_characters
  belongs_to :organization
  has_many :posts
	attr_accessor :places
end

eventManager/app/controllers/events_controller.rb
class EventsController < ApplicationController  
	@places = Place.all
  # GET /events
  def index
    @events = Event.all
    #here is just listing the events that starts after today
    @events = @events.future_events(Date.today)    
    for event in @events
      @places = Place.all
      event.places = @places      
      @place = event.places.find(event.place_id)
      event.places = @place
    end
  end
  # GET /events/1
  def show
    @places = Place.all
    @event = Event.find(params[:id])    
    @event.places = @places
    id = @event.place_id
    @place = Place.find(@event.place_id) if @event.place_id
    @event.places = @place
    @organizations = Organization.all
    orgid = @event.organization_id
    @organization = @organizations.find(orgid) if @event.organization_id
  end
  # GET /events/new
  def new
    @places = Place.all
    @event = Event.new
    @event.places = @places #so I can get the places for the new event form
    @user = current_user
  end
  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @places = Place.all
    @event.places = @places #so I can get the places for the edit event form
  end
  # POST /events
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save        
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        current_user.attend(@event)
      else
        format.html { render :new }
      end
    end
  end
  # PATCH/PUT /events/1
  def update
    @user = current_user
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  # DELETE /events/1
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end
    
  private
	  def event_params
	    params.require(:event).permit(
	      :name, :introduction, :place_id, :begin_date, :finish_date, :places, :is_secret, :creator_id, :organization_id, :active)
	  end	
end

eventManager/app/helpers/events_helper.rb
module EventsHelper
end

eventManager/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :introduction %><br>
    <%= f.text_field :introduction %>
  </div>
  <div class="form-group">
    Place: <br>
    <%= f.select :place_id, @event.places.collect { |p| [ p.name, p.id ] }, include_blank: true  %>
  </div>
  <% if current_user.organizations %>
    <div class="form-group">
      Organization: <br>
      <%= f.select :organization_id, current_user.organizations.collect { |p| [ p.name, p.id ] }, include_blank: true  %>
    </div>
  <% end %>
  <div class="form-group">
    From: <br>
    <%= f.date_field :begin_date %>
  </div>
  <div class="form-group">
    to: <br>
    <%= f.date_field :finish_date %>
  </div>
  <div class="form-group">
    You want the event to be secret for now? 
    Yes: <%= f.radio_button(:is_secret, true) %>
    No: <%= f.radio_button(:is_secret, false) %>    
  </div>
  <%= f.hidden_field :creator_id, :value => current_user.id %>
  <div>
    <%= f.submit %>
  </div
<% end %>

eventManager/app/views/events/_index.html.erb
<div class="alert alert-info">
  <h2>Listing Events</h2>
  <%= link_to 'New Event', new_event_path, role: "button", class: "btn btn-success"  %>
</div>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Introduction</th>
        <th>Place</th>
        <th>From:</th>
        <th>To:</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>          
          <td><%= event.name %> <br> </td>
          <td><%= event.introduction %> <br> </td>
          <td><%= event.places.name if event.places %> <br> </td>        
          <td><%= event.begin_date %> <br> </td>
          <td><%= event.finish_date %> <br> </td>
          <td><%= link_to 'Join', attendances_path(event_id: event.id), method: :post, role: "button", class: "btn btn-success"%> <br> </td>
          <td><%= link_to 'Show', event, role: "button", class: "btn btn-default" %> <br> </td>
          <% if current_user && ((current_user.role === "superadmin") || (event.creator_id === current_user.id)) %>
            <td><%= link_to 'Edit', edit_event_path(event), role: "button", class: "btn btn-default" %> <br> </td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, role: "button", class: "btn btn-default" %> </td>
          <% end %>
          <% if current_user && (current_user.role === "admin") %>
            <td><%= link_to 'Admin', event_admin_panels_path(event_id: event.id), method: :get, role: "button", class: "btn btn-default" %> </td>            
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

eventManager/app/views/events/_show.html.erb
<div class="col-xs-4">
  <div class="well">
    <strong>Name:</strong></br>
    <%= @event.name %>
  </div>
  <div class="well">
    <strong>Introduction:</strong></br>
    <%= @event.introduction %>
  </div>
  <div class="well">
    <strong>Place:</strong></br>
    <%= @place.name if @place%>
  </div>
  <div class="well">
    <strong>Organization:</strong></br>
    <%= @organization.name if @organization%>
  </div>
  <div class="well">
    <strong>From:</strong></br>
    <%= @event.begin_date %>
  </div>
  <div class="well">
    <strong>To:</strong></br>
    <%= @event.finish_date %>
  </div>
  <% if (current_user.role === "superadmin") || (current_user.id === @event.creator_id) %>
    <%= link_to 'Edit', edit_event_path(@event) %> |
  <% end %>
  <%= link_to 'Back', events_path %>
</div>

eventManager/app/views/events/edit.html.erb
<div class="col-xs-4">
	<h2>Editing Event</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @event %> |
	<%= link_to 'Back', events_path %>
</div>

eventManager/app/views/events/new.html.erb
<div class="col-xs-4">
	<h1 class="bg-primary">New Event</h1>

	<%= render 'form' %>

	<%= link_to 'Back', events_path %>
</div>

eventManager/app/views/events/show.html.erb
<%= render "show" %>