eventManager/config/routes.rb
Rails.application.routes.draw do
  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  match '/logout',  to: 'sessions#destroy', via: 'delete'

  match '/signup',    to: 'users#new',    via: 'get'
  match '/welcome',    to: 'welcome#show',    via: 'get'
  root 'welcome#index'

  match '/admin',    to: 'admin#show',    via: 'get'
  
  match 'assigned_characters/:character_id/:event_id',    to: 'assigned_characters#create',    via: 'post', as: :assign

  resources :attendances, only: [:create, :index]
  resources :users
  resources :events
  resources :places
  resources :welcome, only: [:show, :index]
  resources :posts
  resources :organizations
  resources :characters
  resources :user_organizations, only: [:create, :index]
  resources :assigned_characters
  resources :admin, only: [:show]
  resources :event_admin_panels, only: [:index]

end

eventManager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>EventManager</title>
  	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
	  <link rel="stylesheet" href="/main.css" />
</head>
<body padding-top: "70px" class="modal-open">
<div class="container">
	<div class="row">		
		<div class="col-xs-12">
			<nav class="navbar navbar-default">			  
			    <div id="top_bar">
				    <div class="row">
				    	<span style= padding-right="95">
					    	<a href="/" > <img src="/larp-peque.png" alt="larp manager logo" style= height="120"; width="120"; > </a>
					    </span>
						    <% if logged_in? %>
							    <span id="photo_avatar">
							    	<%= image_tag current_user.avatar.url(:thumb) %>
							    </span>	
						</div>
					  <div class="row">
					    <div class="col-xs-6">
					    	<div class="well" id="user_greetings"><strong> Hello,  <%= current_user.name %> -</strong> </div>		 
					    </div> 
					    <div class="col-xs-6">    
					      <div class="well">					      	
					      	<span id="log">
						      	<%= link_to 'Logout', logout_path, method: :delete %> |
										<%= link_to 'Profile', welcome_path%><br>
									</span>
									<% if current_user.role == "admin" %>
					      		<span id="log"><%= link_to 'Admin Panel', admin_path%><span>
					      	<% end%>			
					      </div>		      
				      </div>	
				    </div>	      
				    <% else %>
				    	<div class="well" id="log_in">
				      	  <%= link_to 'Signup', signup_path %> |
				      	  <%= link_to 'Login', login_path %>
				    	</div>
				    <% end %>				    
				</div>			  
			</nav>		
			<% flash.each do |key, msg| %>
				<%= content_tag :div, msg, id: key, class: "alert alert-danger", role: "alert", style: "color: green;" %>
			<% end %>	  
		</div>
	</div>
	<div class="row">		
		<div class="col-xs-3">
			<div class="list-group">
  			<a href="/events" class="list-group-item active">Events</a>
			  <a href="/organizations" class="list-group-item">Organizations</a>
			  <a href="/" class="list-group-item active">Profile</a>
			  <% if current_user && current_user.role === "admin"%>
				  <a href="/users" class="list-group-item">Users</a>
				  <a href="/characters" class="list-group-item active">Characters</a>
				<%end%>
				<% if current_user && current_user.role === "superadmin"%>
				  <a href="/users" class="list-group-item">Users</a>
				  <a href="/characters" class="list-group-item active">Characters</a>
				  <a href="/posts" class="list-group-item">Posts</a>
				<%end%>
			</div>
		</div>
		<div class="col-xs-9" style="overflow-y: scroll; border: 1px; width: 850px; height: 400px;">
			<%= yield %>
		</div>		
	</div>
</div>	
<footer class="footer">	
</footer>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>

</body>
</html>